apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{DEPLOY_NAME}}-destinationrule-mtls
spec:
  host: {{DEPLOY_NAME}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1